# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Install BATS
        uses: mig4/setup-bats@v1.0.1
        with:
          bats-version: 1.1.0

      - name: Install JQ
        run: sudo apt-get install jq

      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run tests
        shell: bash
        run: find "$GITHUB_WORKSPACE/test" -name '*.bats' | xargs bats
        env:
          OC_ADMIN_PWD: ${{ secrets.OC_ADMIN_PWD }}
          OC_TEST_ADMIN_PWD: ${{ secrets.OC_TEST_ADMIN_PWD }}
          OC_TEST_REST_PWD: ${{ secrets.OC_TEST_REST_PWD }}
          OC_HOST_NAME: ${{ secrets.OC_HOST_NAME }}
